### ISSUE TITLE
Support for using custom subnet ranges.

### ISSUE THREAD

**Issue by elric392** [EngineerBetter/concourse-up#10]
Is it possible to define the CIDR blocks that are used for the 'public/private/rds-a/rds-b' subnets?

**Comment by peterellisjones** [comment]
Hi elric392,

The subnets are hard-coded here:
https://github.com/EngineerBetter/concourse-up/blob/master/terraform/template.go#L473-L495

If you modify these and compile from source using the [build_local.sh](https://github.com/EngineerBetter/concourse-up/blob/master/build_local.sh) script you'll be able to use different CIDR ranges for the subnets.

**Comment by elric392** [comment]
Used the build_local.sh and was able to modify the CIDR blocks used, as well as a few other parameters.  Thank you for that advise.

Another issue arose afterward, and wanted to see if my thoughts are correct.  When using the build_local.sh to utilize custom CIDR blocks, you will not be able to utilize the 'self-update' pipeline. Correct?

**Comment by peterellisjones** [comment]
@elric392 ah good catch. Yes you'll have to disable self-update. We don't currently have a flag for that so you'll have to watch the deploy and pause the pipeline manually before it triggers.

**Comment by elric392** [comment]
It is paused by default.  Thanks for confirming.
