### ISSUE TITLE
Add support for Windows

### ISSUE THREAD

**Issue by BradleyCulley** [EngineerBetter/concourse-up#107]
It appears that only Linux and Mac are supported today

**Comment by DanielJonesEB** [comment]
Hey @BradleyCulley,

We're archiving this repo as Concourse-Up turned into [Control Tower](https://github.com/EngineerBetter/control-tower).

We're unlikely to ever support the binary working on Windows, as one of the tools that we shell out to (the BOSH CLI) does not support Windows, even with MinGW installed.
