### ISSUE TITLE
Trouble connecting to existing deployment from new computer

### ISSUE THREAD

**Issue by Jdurham2843** [EngineerBetter/concourse-up#11]
Hello, about a month ago I deployed a concourse ci environment with concourse-up, but now that I am on a new computer, when I run the concourse-up info <project-name> command, I get an error saying it can't find the bucket in s3. I have set up my access credentials for aws correctly, and can even see the bucket when I run "aws s3api list-buckets". Is there a way I can get concourse-up to recognize my deployment?

**Comment by peterellisjones** [comment]
Hi John, are you using different versions of concourse-up? If you used a pre 0.3.0 version for the initial deploy unfortunately it won’t be compatible with 0.3.0+ as we changed the region where we saved the config (previously it was always in eu-west-1, and we changed it to match whatever region the user specified). You can download older versions here: https://github.com/EngineerBetter/concourse-up/releases

Cheers,

Pete


On 16 September 2017 at 00:21:30, John Durham (notifications@github.com) wrote:

Hello, about a month ago I deployed a concourse ci environment with concourse-up, but now that I am on a new computer, when I run the concourse-up info command, I get an error saying it can't find the bucket in s3. I have set up my access credentials for aws correctly, and can even see the bucket when I run "aws s3api list-buckets". Is there a way I can get concourse-up to recognize my deployment?

**Comment by Jdurham2843** [comment]
Hey Peter, I downloaded the earlier version and I seemed to get farther into the process. I'm now getting an issue where while running the info command, I'm getting a time out issue when it tries to get into the bosh server. The output  that the terminal gives shows that it is the correct ip address, but it still seems to timeout. Is this a symptom of trying to connect from a different system?

**Comment by peterellisjones** [comment]
Hi John,

Is it possible you have a different IP address? 

As part of the deploy it creates a security group that limits access to the BOSH director to your own IP address. As the info command works needs to connect to the BOSH director, it won’t work from a different IP address.

You can either modify the security group settings to be more permissive, or run the deploy from the other machine. This will cause terraform to update the security group with the machine you’re running it from.

Cheers

Pete


On 16 September 2017 at 01:14:38, John Durham (notifications@github.com) wrote:

Hey Peter, I downloaded the earlier version and I seemed to get farther into the process. I'm now getting an issue where while running the info command, I'm getting a time out issue when it tries to get into the bosh server. The output that the terminal gives shows that it is the correct ip address, but it still seems to timeout. Is this a symptom of trying to connect from a different system?

**Comment by Jdurham2843** [comment]
Hey Peter, redeploying seems to have done it. Thank you very much, have a good weekend!
