### ISSUE TITLE
Detailed error messages

### ISSUE THREAD

**Issue by fralalonde** [EngineerBetter/concourse-up#17]
Related to #16, if the AWS error conditions were relayed to the console with verbose context it would help debugging.
```
Forbidden: Forbidden
        status code: 403, request id: *****
```
might become 
```
Could not create S3 bucket (blah blah)
```

**Comment by karlkfi** [comment]
Similarly confusing AWS error:

```
AccessDenied: Access Denied
	status code: 403, request id: 993B4DBE5A32E82B
```

**Comment by crsimmons** [comment]
Closing this in lieu of https://github.com/EngineerBetter/concourse-up/issues/32 which has more details
