### ISSUE TITLE
Uploading stemcell 'bosh-aws-xen-hvm-ubuntu-trusty-go_agent/3468'... Failed (00:00:00)

### ISSUE THREAD

**Issue by neildmorris** [EngineerBetter/concourse-up#18]
// errors out and exits without finishing

GENERATING BOSH DIRECTOR CERTIFICATE (34.234.219.169, 10.0.0.6)
Deployment manifest: '/tmp/concourse-up593898250/director.yml'
Deployment state: '/tmp/concourse-up593898250/director-state.json'

Started validating
  Downloading release 'bosh'... Skipped [Found in local cache] (00:00:00)
  Validating release 'bosh'... Finished (00:00:01)
  Downloading release 'bosh-aws-cpi'... Skipped [Found in local cache] (00:00:00)
  Validating release 'bosh-aws-cpi'... Finished (00:00:00)
  Validating cpi release... Finished (00:00:00)
  Validating deployment manifest... Finished (00:00:00)
  Downloading stemcell... Skipped [Found in local cache] (00:00:00)
  Validating stemcell... Finished (00:00:00)
Finished validating (00:00:01)

Started installing CPI
  Compiling package 'ruby_aws_cpi/dc02a5fa6999e95281b7234d4098640b0b90f1e6'... Finished (00:01:35)
  Compiling package 'bosh_aws_cpi/04ca340b3d64ea01aa84bd764cc574805785e97c'... Finished (00:00:02)
  Installing packages... Finished (00:00:00)
  Rendering job templates... Finished (00:00:00)
  Installing job 'aws_cpi'... Finished (00:00:00)
Finished installing CPI (00:01:38)

Starting registry... Finished (00:00:00)
Uploading stemcell 'bosh-aws-xen-hvm-ubuntu-trusty-go_agent/3468'... Failed (00:00:00)
Stopping registry... Finished (00:00:00)
Cleaning up rendered CPI jobs... Finished (00:00:00)

creating stemcell (bosh-aws-xen-hvm-ubuntu-trusty-go_agent 3468):
  CPI 'create_stemcell' method responded with error: CmdError{"type":"Unknown","message":"undefined method `set_api' for #\u003cClass:0x00562927945308\u003e","ok_to_retry":false}

Exit code 1
exit status 1

**Comment by danyoung** [comment]
Hi @neildmorris did you resolve your problem?

**Comment by crsimmons** [comment]
Closing as there hasn't been an update in a while. Feel free to reopen if you are still experiencing this.
