### ISSUE TITLE
Database naming is bad, eg 'terraform-20171012154225076100000002'

### ISSUE THREAD

**Issue by analytically** [EngineerBetter/concourse-up#19]
Should reference Concourse.

**Comment by danyoung** [comment]
Have added a feature story for this https://www.pivotaltracker.com/story/show/152474903

**Comment by danyoung** [comment]
Story for this issue is here: https://www.pivotaltracker.com/story/show/152474903

**Comment by Lewiscowles1986** [comment]
I know you've moved to control tower but this should be closed. It seems like user preference and has no bearing on anything
