### ISSUE TITLE
Installation/Startup instructions

### ISSUE THREAD

**Issue by brasskazoo** [EngineerBetter/concourse-up#22]
I think I must be missing something!

I am trying out concourse for our team, and am new to concourse, bosh and go. This project seemed like the easiest way to get up and running in AWS, but I can't work out how to get it started.

Do I need to run `build_local.sh` or `go build`? Do I need to set a `GOPATH`? Out of the box running `concourse-up deploy xyz` doesn't match up to any command in the repo from what I can see.

Also, if I am running this on Bash for Windows, am I going to have a Bad Time? :)

This is the error message I get with both `build_local.sh` and `go build`:
```
main.go:9:2: cannot find package "github.com/EngineerBetter/concourse-up/bosh" in any of:
        /usr/lib/go/src/pkg/github.com/EngineerBetter/concourse-up/bosh (from $GOROOT)
        ($GOPATH not set)
```

Thanks. Really keen to see how Concourse can help visualise our pipelines!

**Comment by DanielJonesEB** [comment]
Hi @brasskazoo,

We stopped publishing Windows releases of the binary as we had no means of testing them. Hence, you'll need to compile from source code using `build_local.sh` in an environment where you've got Bash. 

`build_local.sh` itself calls `go build`, so you'll need to have a working Golang setup, and have `concourse-up` cloned in a proper `$GOPATH`. 

If you have Golang installed already, try using `go get github.com/EngineerBetter/concourse-up` to get the code cloned to your `$GOPATH`, change into that dir, and then run `build_local.sh`.

Let us know how you get on!

**Comment by peterellisjones** [comment]
@brasskazoo (cc @DanielJonesEB )

I've updated our CI pipeline to publish a windows binary, which you can download here: https://github.com/EngineerBetter/concourse-up/releases/tag/0.6.1

Please note that we don't currently have a way to test concourse-up on windows so although we do intensive system tests for the linux build — you'll have to use the windows build "at your own risk"

cheers,

Pete

**Comment by brasskazoo** [comment]
Thanks for that guys, the windows release didn't work for me (I can sympathise with your issues testing on windows). I've ended up creating a centos vagrant environment for concourse, just using the standalone version for now. 

Once I know what I'm doing a bit more I'll introduce the concourse-up build to that centos box!

**Comment by rdunn-Hypr** [comment]
@brasskazoo @DanielJonesEB if your using the windows binary are you still on your own?

Just tried to run an info command on our deployment and got an error. It work fin when using bash on windows. My colleagues use Mac & ubuntu and am use to being the odd one out lol - but just thought I would check. Thanks

**Comment by DefSol** [comment]
@brasskazoo @DanielJonesEB if your using the windows binary are you still on your own? Just tried to run an info command on our deployment and got an error. It work fine when using bash on windows. My colleagues use Mac & Ubuntu and am used to being the odd one out lol - but just thought I would check. Thanks
