### ISSUE TITLE
Support other IaaSes

### ISSUE THREAD

**Issue by joefitzgerald** [EngineerBetter/concourse-up#3]
Given this is built on top of Terraform, one would imagine it is feasible to support other IaaSes, e.g.:

* vSphere
* OpenStack
* GCP
* Azure

Are you open to this kind of evolution? I would imagine it would have implications for the CLI flags you currently support, which appear to be mildly coupled with AWS. Thoughts?

**Comment by danyoung** [comment]
Hi Joe. Yes we're keen to support other IaaS targets. Do you have any order of priority from your perspective? We had expected we'd add GCP support next, but we just need a suitable stretch of beach time to make it happen. Stay tuned!

**Comment by joefitzgerald** [comment]
I think vSphere is our highest priority from that list. There may be a PR forthcoming from our team on that front.

**Comment by elgohr** [comment]
Looking forward to contribute OpenStack support, if you"re ok with that.

**Comment by danyoung** [comment]
Closing this issue for now. We're open to discussion with folks able to provide testing infrastructure for VSphere or Openstack.
