### ISSUE TITLE
Concourse up on an existing infrastructure

### ISSUE THREAD

**Issue by venth** [EngineerBetter/concourse-up#31]
Hi,

I would like to setup concourse on an existing infrastructure. How can I do it using concourse-up? How to provide:
* vpc,
* subnets?

**Comment by fewknow** [comment]
I need the same functionality.  I decided to fork the repo and just edit the terraform code.  Currently I can get it to build locally because of and error.  If I do get it to build I will put in a PR to allow this ability.

**Comment by DanielJonesEB** [comment]
Hi folks,

Our current thinking is that we're unlikely to support this, as we want to maintain Concourse-Up's ability to self-update, and that'll be harder to do when we can't make assumptions about the infrastructure it's deployed on.

What are your use cases? Are there other ways we could make Concourse easy to deploy into those environments?

**Comment by venth** [comment]
My situation is as follows. In the organization I work for there is strict setup comprising vpc, subnets, internet gateways, etc. I cannot create them, I can place only machines inside the design structure. For me it would be awesome when your solution would setup it selves on the already existing vpc, subnets, internet gateway in the private area. In this scenario concourse-up would be responsible for spinning up new machines and of course provisioning them with concourse.

**Comment by fewknow** [comment]
I found using https://github.com/concourse/concourse-bosh-deployment covers all use cases.  You will need to read and learn a little about bosh, bosh cli v2 and how to submit cloud configs and a manifest.   But this allows you to deploy in any VPC and specify anything you want.  I have used it to deploy into my current AWS VPC and have no issues

**Comment by venth** [comment]
Thanks for the tip 😀
