### ISSUE TITLE
Can not build locally

### ISSUE THREAD

**Issue by fewknow** [EngineerBetter/concourse-up#33]
Current error on build: 
``` 
./main.go:28:15: cannot use commands.Commands (type []"github.com/EngineerBetter/concourse-up/vendor/gopkg.in/urfave/cli.v1".Command) as type []"gopkg.in/urfave/cli.v1".Command in assignment
./main.go:29:12: cannot use commands.GlobalFlags (type []"github.com/EngineerBetter/concourse-up/vendor/gopkg.in/urfave/cli.v1".Flag) as type []"gopkg.in/urfave/cli.v1".Flag in assignment
```

I am having to build locally because I want to use my own VPC and subnets for this.  I have edited the terraform main.tf to accommodate this. 

Any help would be greatly appreciated. 

BTW:  For those new to go(me), you should probably list the dependancies needed for the build including all the `go get github.com/*`  as it took me a while to figure it out. 

Thanks

**Comment by fewknow** [comment]
I got this to work and build locally.  I am going to update the code to allow for -vpc_id, -public_subnet, -private_subnet_a, -private_subnet_b and -office_cidr_blocks(array).  I will put in PR when complete.  

This will allow anyone to deploy into their current VPC.

**Comment by takeyourhatoff** [comment]
In case anybody else hits this, this is a result of attempting to build outside of  your `$GOPATH`.
With `concourse-up`, or any other Go program, you must clone the repository in a specific location. `go get` handles this for you. if you `go get -d github.com/EngineerBetter/concourse-up` the repository will be cloned in `$GOPATH/src/github.com/EngineerBetter/concourse-up` and the build local script will work.
