### ISSUE TITLE
credhub cli timeout breaks security

### ISSUE THREAD

**Issue by engrun** [EngineerBetter/concourse-up#39]
We are experiencing a 30 second timout for the credhub login.

This behaviour encourages all developers to set the password in their bashrc/zshrc files, meaning security is flawed as the password is suddenly exposed in files on every users computer.
This behaviour is now being observed after upgrading to 0.8.4, which includes credhub 1.7.2

**Is is possible to bump the token timeout to a more reasonable length?**

See https://github.com/cloudfoundry-incubator/credhub/issues/32  for related info.

**Comment by DanielJonesEB** [comment]
Hi @engrun,

What kind of time would you consider to be reasonable? Do your engineers have AWS credentials handy that could be used alongside `concourse-up info name --env` to get the CredHub credentials as env vars?

**Comment by engrun** [comment]
I would consider 24 reasonable.
All developers have their own AWS credentials, yes  (if that was you question?)

**Comment by crsimmons** [comment]
Based on the credhub issue linked above I think this was resolved by https://github.com/EngineerBetter/concourse-up/commit/dc7651166aa6cc15ed500217cf91b294af52afe9#diff-88661a05fd6c903df03ea1046a826434

Feel free to reopen the issue if you are still experiencing these timeouts.
