### ISSUE TITLE
Support other instance types

### ISSUE THREAD

**Issue by jgeorge300** [EngineerBetter/concourse-up#4]
Currently, concourse-up is hard coded to use m3 instances. m3's are not available in some of the newer regions (e.g. us-east-2 only has m4's) Need some ability to pass in the preferred types.

**Comment by edude03** [comment]
I was just about to ask for the same thing

**Comment by danyoung** [comment]
Thanks for the heads up! We now have a story placeholder for this and will investigate further https://www.pivotaltracker.com/story/show/150161508

**Comment by danyoung** [comment]
We have switched from using m3.mediums to t2.mediums and m4.mediums as these are available in all regions. Release 0.3.0 is here https://github.com/EngineerBetter/concourse-up/releases/tag/0.3.0
