### ISSUE TITLE
Upgrade concourse-up to 3.13

### ISSUE THREAD

**Issue by engrun** [EngineerBetter/concourse-up#43]
concourse-up is falling behind the concourse releases. 
Recently 3.13.0 was released, concourse-up is still on 3.9.2

We are seriously affected by performance issues due to the Docker overlay driver, which has been fixed/reverted back to btrfs in 3.10 and upwards. 

Can you provide som insight into your roadmap for upgrading concourse-up?

**Comment by engrun** [comment]
In the meantime, is it possible to override the driver settings in a bosh descriptor so that we can use btrfs in 3.9.2 ?

**Comment by engrun** [comment]
@danyoung sorry to stress this matter.  Do you have some sort of estimate for this issue?  
It would be useful to know wether its days, a week or several weeks

**Comment by danyoung** [comment]
@engrun this is more likely to be weeks than days, due to our availability.

**Comment by crsimmons** [comment]
@engrun We've resolved the issues we were seeing and have released [a new version](https://github.com/EngineerBetter/concourse-up/releases/tag/0.8.8). I'm going to mark this issue as resolved.

**Comment by engrun** [comment]
thanks!
