### ISSUE TITLE
Included Terraform (0.10.4) version does not support eu-west-3 region

### ISSUE THREAD

**Issue by saedalavinia** [EngineerBetter/concourse-up#47]
Attempting to run the latest concourse-up release with "--region eu-west-3" results in ERROR because Terraform version 0.10.4 does not support eu-west-3. 
The minimum Terraform version that supports eu-west-3 is 0.11.4

**Comment by DanielJonesEB** [comment]
We had a build all ready to go, but it looks like BOSH can't currently deploy onto M5 instances.

Firstly, the stemcell AMI needs to be configured with ENA enabled, and currently that does not appear to be the case: https://www.pivotaltracker.com/n/projects/1133984/stories/154850804

Secondly, the BOSH Agent is unable to find volumes on M5 instances which use NVMe devices: https://www.pivotaltracker.com/n/projects/956238/stories/152934904

It's possible to build a custom stemcell, and it'd need a fixed BOSH Agent installed in it. This work is definitely out of scope for Concourse-Up though!

**Comment by crsimmons** [comment]
Once the necessary changes are made available on the BOSH side I've got the transition to M5 instances ready to go in a branch on concourse-up.

**Comment by saedalavinia** [comment]
Hey guys! 
Thanks for such a quick response! :+1: 
I guess we will have to wait for CPI. 
The alternative regions seem to be a good temp solution. 
Thanks again! :smile:

**Comment by crsimmons** [comment]
As an update on this for anyone following the issue, I tested this again at the beginning of July and it still doesn't work. The worker vm gets launched but the director is unable to talk to it so it gets shut down after a timeout.

**Comment by crsimmons** [comment]
This is now resolved in https://github.com/EngineerBetter/concourse-up/releases/tag/0.15.1

It ended up being harder than expected for a variety of reasons but the team figured it out in the end.
