### ISSUE TITLE
Make the internal configuration region configurable

### ISSUE THREAD

**Issue by jgeorge300** [EngineerBetter/concourse-up#5]
The documentation states that the internal configuration is always stored in eu-west-1. This should be configurable as some organizations have regulatory requirements on where they can store data.

I was able to change the hard coded region to my preferred region for the moment.

**Comment by danyoung** [comment]
It would be useful to have this. Would putting configuration and deployment in the same region meet your needs, or would you want them to be independently configurable? Also, do you have any thoughts on how you would like the user interface to handle this? Something like a --config-region flag? Story placeholder is here https://www.pivotaltracker.com/story/show/150161466

**Comment by jgeorge300** [comment]
I believe configuration and deployment in the same region will meet the needs of most. I think the "--region" flag is sufficient.

**Comment by danyoung** [comment]
We now store configuration in the same region as deployment. Story accepted here https://www.pivotaltracker.com/story/show/150161466
Release is here https://github.com/EngineerBetter/concourse-up/releases/tag/0.3.0
