### ISSUE TITLE
Ability to specify subnet and custom tags

### ISSUE THREAD

**Issue by dannykansas** [EngineerBetter/concourse-up#50]
A couple questions/suggestions:

1. We tag everything for cost allocation, so it'd be great to be able to specify these tags as part of the deploy process, e.g.:

   `--add-tag "Key=Team,Value=CI" --add-tag "Key=Environment,Value=staging"`

    Right now, this is just a manual process, which means tags are not automatically applied with instance changes. Am I missing this somewhere?

2. Specifying existing VPCs/Subnets to deploy into (in addition to just region) seems pretty crucial for most use cases

**Comment by crsimmons** [comment]
Hi @dannykansas 

1. You are correct, this is not something we currently support. I have added [a story](https://www.pivotaltracker.com/story/show/159109382) to our tracker but I cannot give an estimate on when it will be scheduled or completed.
2. Currently `concourse-up` will terraform a new VPC/Subnets in AWS as part of the deployment process. Deploying to pre-existing VPCs/Subnets is not a use case we have considered.

**Comment by dark5un** [comment]
Hi @dannykansas ,
  EC2 tagging has been introduced with this [release](https://github.com/EngineerBetter/concourse-up/releases/tag/0.13.3).

**Comment by dannykansas** [comment]
Great news - thanks for tagging me with the update.
