### ISSUE TITLE
GCP anytime soon?

### ISSUE THREAD

**Issue by aegershman** [EngineerBetter/concourse-up#51]
Poking through the source code, I noticed this hidden cli arg:
https://github.com/EngineerBetter/concourse-up/blob/master/commands/deploy.go#L70

added ~10 months ago as a part of this commit: https://github.com/EngineerBetter/concourse-up/commit/c2a7bc0ba37e2b68eb2e1b74888723d6c7760a97

Similar to #3 but smaller in scope-- do you have any plans to support GCP anytime soon?

Thanks!

**Comment by DanielJonesEB** [comment]
Thanks for popping by, @aegershman. It's something we're considering, and we have a story in the icebox for. There's some preliminary refactoring that needs to be done first though, and back/restore is higher in the backlog for now.

Interested to hear your use cases, and any features in particular that would be valuable.

**Comment by aegershman** [comment]
Awesome, thanks for your time. Thanks for your contributions to the community, you're making our lives much better & less stressed.

Also, minor side note, I encapsulated the workflow of `concourse-up` in a concourse pipeline: `concourse-up-up`: https://github.com/aegershman/concourse-up-up
