### ISSUE TITLE
Is Concourse 4 w/ Credhub 2.0 safe?

### ISSUE THREAD

**Issue by aegershman** [EngineerBetter/concourse-up#58]
Judging by this comment by the credhub PM, it seems like the concourse/credhub integration might be a little... flakey? https://github.com/concourse/concourse/issues/2293#issuecomment-411566496

Just wondering if you had any thoughts on their comment about recommending against going to credhub 2.0

**Comment by crsimmons** [comment]
Interesting. We hadn't seen that issue - thanks for pointing it out.

Our CI picked up the new version of credhub automatically and it passed all our system tests. That said, those tests aren't focused on rigorously testing all credhub use-cases.

We'll discuss this internally then decide if we should patch Concourse-up with credhub 1.x.

If anyone is aware of any known problems with credhub 2.x in Concourse 4 we would be very interested in hearing about them.

**Comment by crsimmons** [comment]
We have been running Credhub 2 in combination with Concourse 4 on our own Concourse for some time now and haven't encountered any issues. I'm going to close this but if anyone encounters anything that seems related to Credhub 2 feel free to open a new issue.
