### ISSUE TITLE
Unable to add Oauth with Concourse 4.0

### ISSUE THREAD

**Issue by adamclark-dev** [EngineerBetter/concourse-up#59]
Due to concourse moving OAuth configuration into the concourse command from fly, we are now unable to figure out how to configure OAuth, any ideas?

**Comment by danyoung** [comment]
Hi @adamclark-dev - there have certainly been a lot of changes to the way authentication works in Concourse 4.0. We'd like to make sure we adapt Concourse-Up to support the new ways of doing things. Some questions:

- Are you using GitHub oAuth? 
- Are you working on Concourse-Up deployment that was successfully upgraded from v3.x or is this a fresh deployment?
- If this was a upgraded deployment I assume you previously had oAuth fully configured via `fly` ... but this didn't persist?

Thanks

Dan

**Comment by adamclark-dev** [comment]
Closing as now rolled into #62
