### ISSUE TITLE
Accessing concourse-up's bosh

### ISSUE THREAD

**Issue by jgeorge300** [EngineerBetter/concourse-up#6]
I'm still going through the configuration and set-up but is it possible to connect to concourse-up's bosh instance to pull logs from the jobs?

**Comment by DanielJonesEB** [comment]
Hey @jgeorge300 

Thanks for taking an interest and raising these issues. I'm with customers at the moment, so can't respond quickly.

Off the top of my head, details for the Director should either end up in an S3 bucket, or kicking around locally somewhere. I believe a security group rule for the current IP address you ran `concourse-up` from should be added so you can access the Director.

**Comment by crsimmons** [comment]
Hi @jgeorge300 

You can get the credentials for your BOSH director by running `concourse-up info <name>`

As @DanielJonesEB mentioned, the IP from which you first ran `concourse-up deploy <name>` will be whitelisted on the director's security group. If you are on a different IP now you will need to add rules to the security group `concourse-up-<name>-director` allowing your IP over ports 22, 6868, and 25555 (for SSH, BOSH Agent, and BOSH Director CLI access respectively) first.

**Comment by DanielJonesEB** [comment]
@jgeorge300 Closing this, assuming @crsimmons' info helps you.
