### ISSUE TITLE
Concourse extremely slow

### ISSUE THREAD

**Issue by aterreno** [EngineerBetter/concourse-up#69]
Hi guys, we've been using concourse-up for more than a year and all good, but since the upgrade to 4.x everything got painfully slow. 

I've opened this one https://github.com/concourse/concourse/issues/2604 but so far it only got ignored. 

Additionally, we are unable (and I am not sure why) to ssh in the boxes, either downloading the private/pub keys from the json in s3 or with the command line setting up the env variables. 

Can you help? 

Thanks

**Comment by danyoung** [comment]
Hi @aterreno - sorry we missed your original issue. Let's try to work this one out. Could you join us on Slack to help diagnose the issue? https://join.slack.com/t/concourse-up/shared_invite/enQtNDMzNjY1MjczNDU3LTA1NzIxYTZkYjFkMjA2ODBmY2E2OTM3OGE3YTc2OGViNTMxYTY4MjYwNGNjOTAxNDNiOGE5NzhmMTQ2NWVhNzQ

**Comment by aterreno** [comment]
Adding context and infos as we progress this on Slack. 

<img width="887" alt="screenshot 2018-09-26 at 19 05 29" src="https://user-images.githubusercontent.com/76042/46138549-0e670f80-c244-11e8-9b68-5af171789a5d.png">

Cpu at 40+% on idle (no jobs running) 

<img width="1892" alt="htop" src="https://user-images.githubusercontent.com/76042/46138581-2b034780-c244-11e8-9367-dbae2b404e14.png">
<img width="1919" alt="iotop" src="https://user-images.githubusercontent.com/76042/46138582-2b034780-c244-11e8-84a9-96ce911793a6.png">
 
Recreating the worker didn't change the situation, cpu is at min (not even avg) at 40+% 

[concourse.worker.0-20180927-104150-734269313.zip](https://github.com/EngineerBetter/concourse-up/files/2423576/concourse.worker.0-20180927-104150-734269313.zip)

Attached logs of worker when idle.

**Comment by aterreno** [comment]
Closing this one up for now, as performances improved substantially by removing the npm-repo-cache resource from all my pipelines (20~)
