### ISSUE TITLE
Question: Does the terraform script create a new VPC?

### ISSUE THREAD

**Issue by akoranne** [EngineerBetter/concourse-up#7]
Are all the resources put under a VPC or are they just EC2 instances?

Thanks,
--ajay

**Comment by peterellisjones** [comment]
Hi @akoranne 

I creates all instances in a new VPC.

You can look at https://github.com/EngineerBetter/concourse-up#what-it-does for a list of exactly what AWS infrastructure is created

cheers,

Pete
