### ISSUE TITLE
STS & Temporary Credentials 

### ISSUE THREAD

**Issue by pekzeki** [EngineerBetter/concourse-up#71]
Hi, I want to use concourse-up with temporary security credentials but receiving the following error,

> Forbidden: Forbidden
> 	status code: 403, request id: Xyz..., host id: Xyz..

Is it possible to run concourse-up deploy with temp credentials including,
> AWS_PROFILE
> AWS_SECRET_ACCESS_KEY
> AWS_SESSION_TOKEN 

?

If not, are you planing to support _temporary security credentials_ in the near future? 
Thank you all for the great library.

**Comment by pekzeki** [comment]
I think the error was related with S3 buckets. Seems like I resolved it. 
Closed the issue.

**Comment by dark5un** [comment]
And I was about to message you. When you get forbidden status is mainly S3 related. Sorry for the delayed answer.
