### ISSUE TITLE
Check log files of web or worker nodes

### ISSUE THREAD

**Issue by lorands** [EngineerBetter/concourse-up#74]
Can't find a way to access web and worker concourse log files.

**Comment by crsimmons** [comment]
Hi @lorands,

As `concourse-up` uses BOSH to deploy Concourse, you can use `bosh` to get the logs.

First export the correct env vars

```
eval "$(concourse-up --region <region> info <deployment-name> --env)"
```

Then ssh to either the web or one of the workers

```
bosh ssh web
# or
bosh ssh worker/0
```

Process logs can be found in `/var/vcap/sys/log` (you'll need to be root to get to it so run `sudo -i` first)

Does this answer your question?

**Comment by lorands** [comment]
Hi @crsimmons , 

That is exactly what I was looking for! Thanks!!

Regards, 
L.

**Comment by crsimmons** [comment]
Great! 👍
