### ISSUE TITLE
Inbound security rule to allow web worker to connect to itself on port 8844 missing

### ISSUE THREAD

**Issue by steveYeah** [EngineerBetter/concourse-up#78]
After running `concourse-up deploy` with an added `--allow-ips` to an existing and running Concourse, Concourse was no longer able to connect to Credhub. 

We solved this by manually adding an inbound rule for the web instance to allow itself to access itself via its public IP address on the credhub port 8844.

I know there was some work a while back to auto add security rules for internal operation when adding the `--allow-ips` option, so I’m guessing the web worker inbound on port 8844 was missed

**Comment by crsimmons** [comment]
Thanks for raising! We have addressed this in https://github.com/EngineerBetter/concourse-up/releases/tag/0.16.3

**Comment by steveYeah** [comment]
Amazing! Thanks @crsimmons and all 👍
