### ISSUE TITLE
Check for whitelisted IP fails for CIDR ranges other than /32

### ISSUE THREAD

**Issue by sneakybeaky** [EngineerBetter/concourse-up#79]
Checking that the user's IP is present in the `concourse-up-xxxx-director` AWS security group succeeds only if it is present as a /32 range, e.g. `89.197.181.42/32`. When any other range is present the check fails, even if the IP is present in the range.

In our case we had entries in the SG in the form of `89.197.181.40/29`. The check failed when we ran behind the IP `89.197.181.42`

**Comment by crsimmons** [comment]
Thanks for raising! We have addressed this in https://github.com/EngineerBetter/concourse-up/releases/tag/0.16.3
