### ISSUE TITLE
Creating concourse in wrong region

### ISSUE THREAD

**Issue by akoranne** [EngineerBetter/concourse-up#8]
Hi, 

I set AWS_DEFAULT_REGION=us-east-1, yet it created everything in "eu-west-1".

Shouldn't it create the bosh director and concourse in AWS_DEFAULT_REGION that I set?

I probably made some mistake somewhere. Can you please help me point in the right direction?

Thanks,
--ajay

**Comment by peterellisjones** [comment]
Hi @akoranne,

You need to use the `--region` flag to set the region (see https://github.com/EngineerBetter/concourse-up/#region-configuration)

AWS_DEFAULT_REGION is used by terraform to authenticate with AWS — I agree this is confusing so I'll look into whether we can remove this requirement.

cheers,

Pete

**Comment by akoranne** [comment]
Hi Pete,

Thank you for your reply.

Another question, is there a way to put in a username or at a minimum
provide a password (that I want) to Concourse? Where can I modify that?

I downloaded your project and not able to locate where the password is set.
If you can point me, I can change it to my password and rebuild the binary.

Please let me know. Thank you for your help!

With Regards,
--ajay
Ajay S. Koranne
(303) 887.2777

**Comment by peterellisjones** [comment]
Hi @akoranne,

The concourse password is randomly generated here: https://github.com/EngineerBetter/concourse-up/blob/master/config/config.go#L60

You can also change the password by editing the config file on AWS. This will be in a bucket with a name like `concourse-up-mydeployment-config` in a file called `config.json`. Change the `concourse_password` field in this file, save it, and run `concourse-up deploy` again to update the password.

**Comment by akoranne** [comment]
Thank you Pete!

With Regards,
--ajay
Ajay S. Koranne
(303) 887.2777
