### ISSUE TITLE
Forbidden

### ISSUE THREAD

**Issue by mhausmann-pivotal** [EngineerBetter/concourse-up#9]
Just getting the following error when trying to deploy. AWS CLI is configured with a valid IAM account with full access to S3, Route53, EC2, RDS and VPC.

`# concourse-up deploy ci --region eu-west-2 --domain ci.aws.domain.com
Forbidden: Forbidden
	status code: 403, request id: A351BAF8B8B2DA4F`

I have tested with no flags and get the same result.

**Comment by peterellisjones** [comment]
Hi @mhausmann-pivotal can you tell me which release you are using?

**Comment by mhausmann-pivotal** [comment]
Hi @peterellisjones I'm using Concourse-Up version 0.2.59

**Comment by peterellisjones** [comment]
@mhausmann-pivotal are you in the London office? We're on the second floor next to the reception desk. I've not seen the error before so if you're around we could try debugging it together.

**Comment by mhausmann-pivotal** [comment]
@peterellisjones I'm not in today, but could do a Zoom. I'll drop you a mail.

**Comment by peterellisjones** [comment]
@mhausmann-pivotal cool — I'm peter.jones@engineerbetter.com
