### ISSUE TITLE
dns challenge clean up fails on GCP

### ISSUE THREAD

**Issue by vchrisb** [EngineerBetter/concourse-up#90]
I had a slow dns propagation on my side and the `acme: Waiting for DNS record propagation` timed out after 10 minutes.
At the next run the step `acme: Cleaning DNS-01 challenge` fails with trying to clean up the wrong DNS entry: 
`acme: error cleaning up: googlecloud: no matching domain found for domain domain.com.`

My concourse domain is though `ci.gcp.domain.com` and the zone `gcp.domain.com` is in GCP.
It looks like the clean up task is using the wrong domain.

The next run does not try to clean up again and hence start successfully from the beginning.

**Comment by vchrisb** [comment]
closing for now. I was not able to reproduce.

**Comment by DanielJonesEB** [comment]
Thanks for reporting, @vchrisb. Please re-open and let us know if you encounter this again.
