### ISSUE TITLE
0.20.0 release notes typo

### ISSUE THREAD

**Issue by mdcarlson** [EngineerBetter/concourse-up#93]
The GCP section of the 0.20.0 release notes contains the following:

`BOSH AWS CPI 29.0.0`

Pretty sure that is supposed to reference GCP.  The download link is correct.  

There... I've added value today!  ;-)

**Comment by DanielJonesEB** [comment]
_Mmmm_, nothing quite like tasty copypasta.

Thanks for pointing this out, we'll fix that :)

**Comment by crsimmons** [comment]
I've fixed it in the 0.20.0 release. Will also fix the script that generates that part of the release notes.
