### ISSUE TITLE
InfluxDB has default retention policy resulting in out of disk on web node

### ISSUE THREAD

**Issue by sneakybeaky** [EngineerBetter/concourse-up#95]
concourse-up version 0.15.1.

After around 80 days of running our setup the web node ran out of disk. After some investigation we saw that InfluxDB had consumed all disk. Further digging showed that it had just the default retention policy which has an infinite duration.

**Comment by sneakybeaky** [comment]
After raising this in the concourse-up slack @dark5un commented : 

> Got it, we have retention-autocreate=true which according to docs:

> _Enables the automatic creation of the DEFAULT retention policy autogen when a database is created. The retention policy autogen has an infinite duration and is also set as the database's DEFAULT retention policy, which is used when a write or query does not specify a retention policy. Disable this setting to prevent the creation of this retention policy when creating databases._

**Comment by evadinckel** [comment]
Hello @sneakybeaky,

Thanks for reaching out to us and for raising interesting questions on this matter.
This is just to inform you that we have acknowledged your issue by creating a task in our workflow tracker.
We will get back to you as soon as our engineers come to a solution.

Thanks,
Best regards
Eva

**Comment by evadinckel** [comment]
Hello @sneakybeaky,

Hoping you're well today.
This is to let you know that this is now fixed: we have made sure that the retention policy on InfluxDB is now extended to 28 days to prevent out of disk space on the web node.
Patch release available here: https://github.com/EngineerBetter/concourse-up/releases/tag/0.20.2.

Thanks!

**Comment by sneakybeaky** [comment]
Thank you for all your hard work on this great product :-)
