### ISSUE TITLE
GCP empty bucket name

### ISSUE THREAD

**Issue by glend** [EngineerBetter/concourse-up#99]
Hi, I'm trying to deploy the setup in GCP, using version 0.20.2. I followed the docs and created a service account, and assigned Project Owner permissions to it (+Storage Admin+Storage Object Admin). However when running the following:

```
concourse-up deploy \
  --iaas gcp \
  --region "europe-west1" \
  --namespace test \
  --domain "https://concourse.xxx.xxx.xx" \
  --workers 3 \
  --worker-size xlarge \
  --web-size medium \
  --db-size medium \
  --github-auth-client-id xxx \
  --github-auth-client-secret xxx \
  --preemptible=true \
  xxx
```

I get the following:

> error getting initial config before deploy: [error determining if config already exists [storage: bucket name is empty

If I remove the `--iaas` flag it tries to deploy to my AWS account and doesn't have an issue determining the bucket name.

**Comment by crsimmons** [comment]
Hi @glend,

I'm not sure why concourse-up is failing to find the config. I'm still investigating that.

One problem I can see with your command is that the domain should not include the protocol. So in your case it should be `--domain concourse.xxx.xxx.xx`.

**Comment by glend** [comment]
@crsimmons I actually fixed it by setting my GCP user to be able to use the service account (during service account creation). I thought we could just use the service account without any user?

**Comment by crsimmons** [comment]
You don't need to associate the service account with a user. When you create the account you just need to give it Project Owner permissions then generate a JSON key file. Then you can `export GOOGLE_APPLICATION_CREDENTIALS=<path/to/creds.json>` and deploy.

**Comment by glend** [comment]
Closed as this was my fault when recreating service account.
